# Project information
site_name: Selene
site_url: https://yashaka.github.io/selene/
site_author: Iakiv Kramarenko
site_description: >-
  User-oriented Web UI browser tests in Python.

# Repository
repo_name: yashaka/selene
repo_url: https://github.com/yashaka/selene
edit_uri: edit/master/docs/

# Page tree
nav:
  - Overview: index.md
  # - Learn Basics:
  #   - Stub Title 1: learn-basics/automate-testing-guide.md
  # - Learn Advanced:
  #   - Stub Title 1: learn-advanced/automate-testing-guide.md
  - FAQ:
    - How to work with iFrames: faq/iframes-howto.md
    - How to work with Shadow DOM: faq/shadow-dom-howto.md
    - How to use custom profile: faq/custom-user-profile-howto.md
    - How to extend Selene [TBD]: faq/extending-selene-howto.md
  # - Use Cases:
  #   - Stub Title 1: use-cases/path-to-some-example.md
  - Reference:
    - Config: reference/configuration.md
    - command.*: reference/command.md
    - query.*: reference/query.md
    - Expected Conditions: reference/condition.md
    - Selene Exceptions: reference/exceptions.md
  - Contribution:
    - How to contribute: contribution/to-source-code-guide.md
    - Code conventions: contribution/code-conventions-guide.md
    - Release workflow: contribution/release-workflow-guide.md
    - How to contribute to docs: contribution/to-documentation-guide.md
    - How to organize docs: contribution/how-to-organize-docs-guide.md
    - How to write docs: contribution/how-to-write-docs-guide.md
  - Changelog: https://github.com/yashaka/selene/releases
  - License: license.md

# Configuration
theme:
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/file-document-edit
    view: material/file-eye
  favicon: assets/images/favicon.png
  logo: assets/images/logo-icon.png
  # custom_dir: docs/overrides
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view

extra:
  version: 2.0.0rc10
  social:
    - icon: material/web
      link: https://autotest.how/sdet-start-ru
      name: Запишись на курс
    - icon: fontawesome/brands/telegram
      link: https://t.me/selene_py_ru
      name: Selene.py на русском
    - icon: material/web
      link: https://autotest.how/sdet-start
      name: Sign up to Selene course
    - icon: fontawesome/brands/telegram
      link: https://t.me/selene_py
      name: Selene.py (in English)
    - icon: material/web
      link: https://autotest.how/sdet-start-uk
      name: Реєструйся на курс


# Plugins
plugins:
  - search
  - macros
  - autorefs
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_section_style: list
            show_docstring_modules: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        CONTRIBUTING.md: contribution/to-source-code-guide.md
        CHANGELOG.md: changelog.md
        LICENSE.md: license.md


# Extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
      restrict_base_path: False
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
